### ISSUE TITLE
Doesn't work for the chess.com games of Daniel Naroditsky

### ISSUE THREAD

**Issue by ghost** [jkingsman/chess-downloader#3]
Hi,

thanks for this great tool :) used it for my own games and it works fine.
But i can't download the chess.com games of GM Daniel Naroditsky.

It has
...
Requesting Chess.com PGN (page 129 of 130)
Requesting Chess.com PGN (page 130 of 130)
Preparing download of 100242 games from Chess.com
Download of DanielNaroditsky_chess.com_2024-03-09.pgn complete!

But there's no pgn.
Any ideas !?

Gilbert

**Comment by jkingsman** [comment]
Hm, interesting. Do you know how to open the browser console? I wonder if maybe there's an error there that could elucidate the problem further. I'm traveling right now, but I'll give this a shot once I'm back and my computer and see what I can figure out.

**Comment by jkingsman** [comment]
Actually, one thing does come to mind. If you just let the page sit for a long time after triggering the download, maybe around 15 or 20 minutes, does the download eventually complete? I'm wondering if that many games is just taking up a lot of memory and your browser needs some extra time to get through them all and compile them into a file for download. That may not be the solution, but it's the best I can do remotely until I get back in front of a computer next week.

**Comment by ghost** [comment]
I'll try. All requests have status 200, no errors.

**Comment by ghost** [comment]
Nothing changed after 30 mins.
Konsole has "Das Cookie "" wurde als Drittanbieter abgelehnt."

**Comment by jkingsman** [comment]
Spotted the issue; looks like the older method of generating a file for download was hitting size restrictions. Now fixed. Give the page a refresh and it and should work for the 295MB (!!!) PGN of Danya's games!

**Comment by ghost** [comment]
Works like a charm :)
Thanks for quick support!
